"""Tests for POLISH.5 — File-tab preview handlers.

The roadmap (M-POLISH item POLISH.5) called for context-appropriate
previews when the user selects a file in the Files tab. The existing
``_preview_file_path`` method handled images + a generic text path;
POLISH.5 added specialized handlers (executed before the text fallback)
for JSON, CSV, 3D-structure (.xyz/.mol/.pdb), HTML, SVG, and cube
files.

These tests exercise the dispatch logic by invoking ``_preview_file_path``
directly with prepared files in ``tmp_path`` and checking the status
message reflects the right preview type. We don't introspect the
``_files_preview_output`` widget content (Output widgets serialize
through Jupyter's display protocol — fragile to test); the status
text + non-raising completion is the contract we lock in.
"""

from __future__ import annotations

import json

import pytest

from quantui.app import QuantUIApp


@pytest.fixture
def app(tmp_path, monkeypatch):
    # Redirect the Files-tab allowed-roots to tmp_path so the preview
    # path-check passes. The cheapest way is to monkeypatch the
    # method — its return value is read directly by _preview_file_path.
    monkeypatch.setenv("QUANTUI_RESULTS_DIR", str(tmp_path))
    a = QuantUIApp()
    monkeypatch.setattr(a, "_files_allowed_roots", lambda: [tmp_path])
    return a


class TestFilePreviewDispatch:
    def test_json_preview_status(self, app, tmp_path):
        p = tmp_path / "result.json"
        p.write_text(json.dumps({"a": 1, "b": [2, 3], "c": "hi"}), encoding="utf-8")
        app._preview_file_path(p)
        assert "JSON preview" in app._files_status_html.value

    def test_csv_preview_status(self, app, tmp_path):
        p = tmp_path / "data.csv"
        p.write_text("freq,intensity\n1600,80\n3700,5\n3800,50\n", encoding="utf-8")
        app._preview_file_path(p)
        status = app._files_status_html.value
        assert "CSV preview" in status
        # Row count appears in the status.
        assert "rows" in status

    def test_html_preview_uses_sandboxed_label(self, app, tmp_path):
        p = tmp_path / "report.html"
        p.write_text("<html><body><h1>Hi</h1></body></html>", encoding="utf-8")
        app._preview_file_path(p)
        assert "HTML preview" in app._files_status_html.value
        assert "sandboxed" in app._files_status_html.value

    def test_cube_preview_shows_metadata_only(self, app, tmp_path):
        # Mock a cube file with a plausible header. Don't pad to a huge
        # size — the handler does NOT read past 6 lines anyway.
        p = tmp_path / "homo.cube"
        p.write_text(
            "Cube file generated by QuantUI test\n"
            "Volumetric data follows\n"
            "    3    0.0    0.0    0.0\n"
            "   40    0.5    0.0    0.0\n"
            "   40    0.0    0.5    0.0\n"
            "   40    0.0    0.0    0.5\n"
            "    1    1.0  0.0  0.0  0.0\n",
            encoding="utf-8",
        )
        app._preview_file_path(p)
        assert "Cube file metadata" in app._files_status_html.value

    def test_text_fallback_for_unknown_extension(self, app, tmp_path):
        p = tmp_path / "notes.txt"
        p.write_text("line one\nline two\n", encoding="utf-8")
        app._preview_file_path(p)
        assert "text file" in app._files_status_html.value

    def test_md_falls_through_to_text(self, app, tmp_path):
        # .md is in text_ext — should land in the text-file preview path.
        p = tmp_path / "README.md"
        p.write_text("# Hello\n\nBody.\n", encoding="utf-8")
        app._preview_file_path(p)
        assert "text file" in app._files_status_html.value

    def test_xyz_attempts_3d_preview_or_falls_through(self, app, tmp_path):
        # If py3Dmol is available the handler renders 3D; otherwise it
        # silently falls through to the text path (the .xyz extension is
        # in text_ext). Either status is acceptable — the contract is
        # "doesn't raise".
        p = tmp_path / "h2o.xyz"
        p.write_text(
            "3\nwater\nO 0 0 0\nH 0.96 0 0\nH -0.24 0.93 0\n", encoding="utf-8"
        )
        app._preview_file_path(p)
        status = app._files_status_html.value
        assert any(
            tag in status for tag in ("3D structure preview", "text file")
        ), f"unexpected status: {status!r}"


class TestFilePreviewAutoOnSelect:
    """Selecting a file in the entries widget should auto-preview it.

    Users reported (session 54) that just clicking a file did nothing —
    they had to additionally click Open. The fix: ``_on_files_entry_changed``
    invokes ``_preview_file_path`` for files (folders still require Open
    so single-click doesn't accidentally navigate).
    """

    def test_selecting_file_triggers_preview(self, app, tmp_path):
        p = tmp_path / "data.json"
        p.write_text('{"x": 1}', encoding="utf-8")
        # Simulate the ipywidgets observe payload that fires on value change.
        app._files_current_dir = tmp_path
        app._on_files_entry_changed({"new": str(p)})
        assert "JSON preview" in app._files_status_html.value

    def test_selecting_folder_does_not_preview(self, app, tmp_path):
        sub = tmp_path / "subdir"
        sub.mkdir()
        app._files_current_dir = tmp_path
        app._on_files_entry_changed({"new": str(sub)})
        # Status should hint at Open, NOT a preview-type tag.
        status = app._files_status_html.value
        assert "click Open" in status
        assert "JSON preview" not in status
        assert "CSV preview" not in status


class TestFilePreviewSafety:
    def test_path_outside_allowed_roots_rejected(self, app, tmp_path, monkeypatch):
        # Tighten allowed roots to a subdirectory; a sibling file must
        # be rejected with a "outside allowed roots" status.
        inside = tmp_path / "inside"
        inside.mkdir()
        outside = tmp_path / "outside.json"
        outside.write_text("{}", encoding="utf-8")
        monkeypatch.setattr(app, "_files_allowed_roots", lambda: [inside])
        app._preview_file_path(outside)
        assert "outside allowed roots" in app._files_status_html.value.lower()

    def test_missing_file_rejected(self, app, tmp_path):
        p = tmp_path / "nope.txt"
        app._preview_file_path(p)
        assert "no longer exists" in app._files_status_html.value.lower()

    def test_invalid_json_falls_through_to_text(self, app, tmp_path):
        # Broken JSON should NOT crash the handler — it falls through
        # to the text preview path.
        p = tmp_path / "broken.json"
        p.write_text("{not valid json", encoding="utf-8")
        app._preview_file_path(p)
        # Either we got the text fallback OR (unlikely) a JSON status
        # message — both indicate non-crash behavior. The contract here
        # is just "didn't raise and surfaced SOMETHING".
        assert app._files_status_html.value
