"""Tests for the M-EXPORT / EXPORT.5 cube + bundle helpers.

Both helpers are pure-Python (shutil + Path) so all tests run on every
platform, no PySCF / RDKit / ASE required.

What we want to lock down:

* ``export_cube`` copies the source cube to ``<result_dir>/<label>.cube``
  with a sanitized label, returns the dest path, and returns ``None`` for
  missing source rather than raising.
* ``export_result_bundle`` zips the whole result folder, places the zip
  as a sibling of the result dir by default, and survives missing dirs.
* The Isosurface panel exposes ``_iso_export_cube_btn`` + status widget,
  and the Export accordion exposes ``_export_bundle_btn`` + status —
  buttons start disabled (no result loaded yet at builder time).
"""

from __future__ import annotations

import zipfile

from quantui.results_storage import export_cube, export_result_bundle


def _write_dummy_cube(path):
    # Minimal cube-looking text; the helpers don't parse it.
    path.write_text(
        "Generated by QuantUI tests\n"
        "Density / orbital values follow\n"
        "    3    0.0    0.0    0.0\n"
        "    1    0.5    0.0    0.0\n"
        "    1    1.0    0.0    0.0\n",
        encoding="utf-8",
    )


class TestExportCube:
    def test_returns_none_when_source_missing(self, tmp_path):
        src = tmp_path / "does_not_exist.cube"
        assert export_cube(src, tmp_path, orbital_label="HOMO") is None

    def test_copies_to_friendly_name(self, tmp_path):
        src = tmp_path / "isosurfaces" / "H2O_HOMO_2026-05-23.cube"
        src.parent.mkdir(parents=True)
        _write_dummy_cube(src)
        dest = export_cube(src, tmp_path, orbital_label="HOMO")
        assert dest is not None
        assert dest == tmp_path / "HOMO.cube"
        assert dest.exists()
        # Content round-trip — copy, not move.
        assert dest.read_text(encoding="utf-8") == src.read_text(encoding="utf-8")
        assert src.exists()

    def test_sanitizes_label(self, tmp_path):
        src = tmp_path / "src.cube"
        _write_dummy_cube(src)
        dest = export_cube(src, tmp_path, orbital_label="HOMO/LUMO gap")
        # Spaces + slash should become underscores; no path traversal.
        assert dest is not None
        assert dest.parent == tmp_path
        assert dest.name.endswith(".cube")
        assert "/" not in dest.name
        assert "\\" not in dest.name

    def test_falls_back_to_orbital_when_label_empty(self, tmp_path):
        src = tmp_path / "src.cube"
        _write_dummy_cube(src)
        dest = export_cube(src, tmp_path, orbital_label="...")
        assert dest is not None
        assert dest.name == "orbital.cube"

    def test_overwrites_existing(self, tmp_path):
        src = tmp_path / "src.cube"
        _write_dummy_cube(src)
        # Pre-create the dest with stale content.
        stale = tmp_path / "HOMO.cube"
        stale.write_text("stale", encoding="utf-8")
        dest = export_cube(src, tmp_path, orbital_label="HOMO")
        assert dest is not None
        assert dest.read_text(encoding="utf-8").startswith("Generated by QuantUI")


class TestExportResultBundle:
    def _populate(self, result_dir):
        result_dir.mkdir(parents=True)
        (result_dir / "result.json").write_text("{}", encoding="utf-8")
        (result_dir / "pyscf.log").write_text("log", encoding="utf-8")
        (result_dir / "isosurfaces").mkdir()
        (result_dir / "isosurfaces" / "HOMO.cube").write_text("cube", encoding="utf-8")

    def test_returns_none_when_result_dir_missing(self, tmp_path):
        assert export_result_bundle(tmp_path / "missing") is None

    def test_returns_none_when_path_is_not_dir(self, tmp_path):
        f = tmp_path / "not_a_dir"
        f.write_text("x", encoding="utf-8")
        assert export_result_bundle(f) is None

    def test_writes_zip_as_sibling_of_result_dir(self, tmp_path):
        rd = tmp_path / "calc_2026-05-23_19-30"
        self._populate(rd)
        out = export_result_bundle(rd)
        assert out is not None
        assert out == tmp_path / f"{rd.name}.zip"
        assert out.exists()

    def test_zip_contains_full_tree(self, tmp_path):
        rd = tmp_path / "calc_xyz"
        self._populate(rd)
        out = export_result_bundle(rd)
        assert out is not None
        with zipfile.ZipFile(out) as zf:
            names = set(zf.namelist())
        # Inside the zip, paths are prefixed with the result-dir name so
        # the extract preserves the source folder.
        assert any(n.endswith("result.json") for n in names)
        assert any(n.endswith("pyscf.log") for n in names)
        assert any(n.endswith("HOMO.cube") for n in names)

    def test_explicit_output_dir(self, tmp_path):
        rd = tmp_path / "calc_xyz"
        self._populate(rd)
        elsewhere = tmp_path / "shareables"
        out = export_result_bundle(rd, output_dir=elsewhere)
        assert out is not None
        assert out.parent == elsewhere
        assert out.exists()


class TestExportButtonsExist:
    """Smoke-check that the builders wired the new EXPORT.5 widgets."""

    def test_iso_cube_and_bundle_buttons_present(self):
        # Importing QuantUIApp here keeps the heavy import out of the
        # module-import path for the helper-only tests above.
        from quantui.app import QuantUIApp

        app = QuantUIApp()
        assert hasattr(app, "_iso_export_cube_btn")
        assert hasattr(app, "_iso_export_status")
        assert hasattr(app, "_export_bundle_btn")
        assert hasattr(app, "_export_bundle_status")
        # Both action buttons start disabled — no data to export yet.
        assert app._iso_export_cube_btn.disabled is True
        assert app._export_bundle_btn.disabled is True

    def test_iso_cube_handler_no_data_path(self, tmp_path):
        from quantui.app import QuantUIApp

        app = QuantUIApp()
        # No cube path set → handler must not raise and must surface a msg.
        app._on_iso_export_cube(None)
        assert app._iso_export_status.value  # non-empty

    def test_bundle_handler_no_result_dir_path(self):
        from quantui.app import QuantUIApp

        app = QuantUIApp()
        # No _last_result_dir → handler must not raise and must surface msg.
        app._on_export_bundle(None)
        assert app._export_bundle_status.value  # non-empty

    def test_iso_cube_handler_happy_path(self, tmp_path):
        from pathlib import Path as _Path

        from quantui.app import QuantUIApp

        app = QuantUIApp()
        src = tmp_path / "src.cube"
        src.write_text("cube body", encoding="utf-8")
        result_dir = tmp_path / "result"
        result_dir.mkdir()
        app._last_cube_path = src
        app._last_cube_orbital = "HOMO"
        app._last_result_dir = result_dir
        app._on_iso_export_cube(None)
        dest = result_dir / "HOMO.cube"
        assert dest.exists()
        assert dest.read_text(encoding="utf-8") == "cube body"
        # Verify the path object types are still Path (not stringified).
        assert isinstance(app._last_cube_path, _Path)

    def test_bundle_handler_happy_path(self, tmp_path):
        from quantui.app import QuantUIApp

        app = QuantUIApp()
        rd = tmp_path / "calc"
        rd.mkdir()
        (rd / "result.json").write_text("{}", encoding="utf-8")
        app._last_result_dir = rd
        app._on_export_bundle(None)
        assert (tmp_path / "calc.zip").exists()


def test_imports_are_public():
    """Sanity: helpers are importable from results_storage public namespace."""
    from quantui import results_storage

    assert hasattr(results_storage, "export_cube")
    assert hasattr(results_storage, "export_result_bundle")
